### ISSUE TITLE
send data to Intel IoT cloud via TCP and UDP 

### ISSUE THREAD

**Issue by microspace** [enableiot/iotkit-samples#35]
Hello
I've tried to send data to cloud via TCP, but no success
```
echo -n '52#{ "n": "temp", "v": 5}' | nc 127.0.0.1 7070
```
I've tried UDP, no success
```
echo -n '{ "n": "temp", "v": 5}' | nc -u 127.0.0.1 41234
```
Output is:
```
BusyBox v1.22.1 (2015-06-19 07:36:41 CEST) multi-call binary.
Usage: nc [IPADDR PORT]
```
maybe I should use some another version of netcat? Something wrong with this version of netcat?

P.S. The only working example is with UDP:
```
echo -n '{ "n": "temp", "v": 5}' > /dev/udp/localhost/41234
```

**Comment by marcinma** [comment]
`echo -n '52#{ "n": "temp", "v": 5}' ` Is wrong since your request have only 22 characters not 52 (52# means length of message), your nc request should be:
`echo -n '22#{ "n": "temp", "v": 5}' | nc 127.0.0.1 7070`
Assuming temp is attached to active device you should see logs in agent (please check /tmp/agent.log)
